#!/bin/bash

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "Usage: . ./setup"
  exit 1
fi

curr_dir="$(dirname "$BASH_SOURCE[0]")"
cd -- $curr_dir && \
source venv/bin/activate
if [[ ! $PYTHONPATH =~ "$(pwd)" ]]; then
  export PYTHONPATH="$PYTHONPATH:$(pwd):"
fi
echo "PYTHONPATH=$PYTHONPATH"

if [[ ! -d "{$curr_dir}/.git/hooks" ]]; then
  echo ".git/hooks directory not found"
  exit 1
fi

if [[ ! -f "{$git_path}/pre-commit" ]]; then
  pre-commit install
fi
